# site setting
title: six
baseurl: /six
tagline: Sample Optin Form


markdown: kramdown
exclude: ['README.md']
permalink: pretty #to remove .html
gems:
  - jekyll-seo-tag
  - jekyll-sitemap
  
include: ['_pages']

